include: package:pedantic/analysis_options.1.11.0.yaml
#  analyzer:
#    errors:
#      prefer_single_quotes: error
#      prefer_const_declarations: error
#      prefer_const_constructors: error
#      missing_required_param: error
#
#  linter:
#    rules:
#      prefer_single_quotes : true
#      prefer_const_declarations: true
#      prefer_const_constructors: true
#      missing_required_param: true